baseurl = ""
languageCode = "en-us"
title = "Stammbaum Essert / Petersen"
theme = "Stammbaum"
googleAnalytics = ""

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more information take a look at the README.

	# To provide some metadata for search engines feel free to add some
	# information about you and your website.
	name = "Claudia Essert"
	description = "Stammbaum der Familient Essert und Petersen"

	# The path must be relative to the static folder
	favicon = "favicon.ico"


	# Navigation
	[params.navigation]
		brand = "Stammbaum Essert / Petersen"

		[params.navigation.links]
			stammbaum  = "Stammbaum"
			petersen   = "Personen Petersen"
			essert     = "Personen Essert"
			urpetersen = "Urkunden Petersen"
			uressert   = "Urkunden Essert"
			statistik  = "Statistik"


	# Stammbaum section
	[params.stammbaum]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		headline    = "Stammbaum der Familien Petersen und Essert"
		description = "Hier kommt der Stammbaum hin."
		buttonText  = "Find out more"


	# Petersen section
	[params.petersen]
		headline = "Personen der Familie Petersen"

        [[params.petersen.list]]
            icon = "fa-diamond"
            title = "Sturdy Templates"
            description = "Our templates are updated regularly so they don't break."

        [[params.petersen.list]]
			      icon = "fa-paper-plane"
			      title = "Ready to Ship"
			      description = "You can use this theme as is, or you can make changes!"

  # Essert section
	[params.essert]
		headline = "Personen der Familie Essert"

		    [[params.essert.list]]
		        icon = "fa-diamond"
		        title = "Sturdy Templates"
		        description = "Our templates are updated regularly so they don't break."

		    [[params.essert.list]]
					  icon = "fa-paper-plane"
					  title = "Ready to Ship"
					  description = "You can use this theme as is, or you can make changes!"

	# Urkunden Petersen section
	[params.urpetersen]
		headline = "Urkunden der Familie Petersen"

				[[params.urpetersen.list]]
					  icon = "fa-diamond"
					  title = "Sturdy Templates"
					  description = "Our templates are updated regularly so they don't break."

	      [[params.urpetersen.list]]
						icon = "fa-paper-plane"
						title = "Ready to Ship"
						description = "You can use this theme as is, or you can make changes!"

	# Essert section
	[params.uressert]
		headline = "Personen der Familie Essert"

				[[params.uressert.list]]
						icon = "fa-diamond"
						title = "Sturdy Templates"
						description = "Our templates are updated regularly so they don't break."

				[[params.uressert.list]]
						icon = "fa-paper-plane"
						title = "Ready to Ship"
						description = "You can use this theme as is, or you can make changes!"


	# Portfolio modals
	[params.portfolio.modal]
        client = "Client"
        date = "Date"
        category = "Category"
        buttonText = "Close"

	# Statistik section
	[params.statistik]
		headline = "Statistik"
		description = "Ready to start your next project with us? That's great! Give us a call or send us an email and we will get back to you as soon as possible!"
		phone = "123-456-6789"
		email = "feedback@startbootstrap.com"
